def Currency():
    currency = ["Afghan Afghani",
                "European Euro",
                "European Euro",
                "Albanian Lek",
                "Algerian Dinar",
                "United States Dollar",
                "European Euro",
                "Angolan Kwanza",
                "East Caribbean Dollar",
                "East Caribbean Dollar",
                "Argentine Peso",
                "Armenian Dram",
                "Aruban Florin",
                "Saint Helena Pound",
                "Australian Dollar",
                "European Euro",
                "Azerbaijan Manat",
                "Bahamian Dollar",
                "Bahraini Dinar",
                "Bangladeshi Taka",
                "Barbadian Dollar",
                "Belarusian Ruble",
                "European Euro",
                "Belize Dollar",
                "West African Cfa Franc",
                "Bermudian Dollar",
                "Bhutanese Ngultrum",
                "Bolivian Boliviano",
                "United States Dollar",
                "Bosnia And Herzegovina Convertible Mark",
                "Botswana Pula",
                "Brazilian Real",
                "United States Dollar",
                "United States Dollar",
                "Brunei Dollar",
                "Bulgarian Lev",
                "West African Cfa Franc",
                "Burundi Franc",
                "Cape Verdean Escudo",
                "Cambodian Riel",
                "Central African Cfa Franc",
                "Canadian Dollar",
                "United States Dollar",
                "Cayman Islands Dollar",
                "Central African Cfa Franc",
                "Central African Cfa Franc",
                "New Zealand Dollar",
                "Chilean Peso",
                "Chinese Yuan Renminbi",
                "Australian Dollar",
                "Australian Dollar",
                "Colombian Peso",
                "Comorian Franc",
                "Congolese Franc",
                "Central African Cfa Franc",
                "New Zealand Dollar",
                "Costa Rican Colon",
                "West African Cfa Franc",
                "Croatian Kuna",
                "Cuban Peso",
                "Netherlands Antillean Guilder",
                "European Euro",
                "Czech Koruna",
                "Danish Krone",
                "Djiboutian Franc",
                "East Caribbean Dollar",
                "Dominican Peso",
                "United States Dollar",
                "Egyptian Pound",
                "United States Dollar",
                "Central African Cfa Franc",
                "Eritrean Nakfa",
                "European Euro",
                "Swazi Lilangeni",
                "Ethiopian Birr",
                "Falkland Islands Pound",
                "Danish Krone",
                "Fijian Dollar",
                "European Euro",
                "European Euro",
                "European Euro",
                "Cfp Franc",
                "Central African Cfa Franc",
                "Gambian Dalasi",
                "Georgian Lari",
                "European Euro",
                "Ghanaian Cedi",
                "Gibraltar Pound",
                "European Euro",
                "Danish Krone",
                "East Caribbean Dollar",
                "European Euro",
                "United States Dollar",
                "Guatemalan Quetzal",
                "Guernsey Pound",
                "Guinean Franc",
                "West African Cfa Franc",
                "Guyanese Dollar",
                "Haitian Gourde",
                "Honduran Lempira",
                "Hong Kong Dollar",
                "Hungarian Forint",
                "Icelandic Krona",
                "Indian Rupee",
                "Indonesian Rupiah",
                "Iranian Rial",
                "Iraqi Dinar",
                "European Euro",
                "Manx Pound",
                "Israeli New Shekel",
                "European Euro",
                "Jamaican Dollar",
                "Japanese Yen",
                "Jersey Pound",
                "Jordanian Dinar",
                "Kazakhstani Tenge",
                "Kenyan Shilling",
                "Australian Dollar",
                "European Euro",
                "Kuwaiti Dinar",
                "Kyrgyzstani Som",
                "Lao Kip",
                "European Euro",
                "Lebanese Pound",
                "Lesotho Loti",
                "Liberian Dollar",
                "Libyan Dinar",
                "Swiss Franc",
                "European Euro",
                "European Euro",
                "Macanese Pataca",
                "Malagasy Ariary",
                "Malawian Kwacha",
                "Malaysian Ringgit",
                "Maldivian Rufiyaa",
                "West African Cfa Franc",
                "European Euro",
                "United States Dollar",
                "European Euro",
                "Mauritanian Ouguiya",
                "Mauritian Rupee",
                "European Euro",
                "Mexican Peso",
                "United States Dollar",
                "Moldovan Leu",
                "European Euro",
                "Mongolian Tugrik",
                "European Euro",
                "East Caribbean Dollar",
                "Moroccan Dirham",
                "Mozambican Metical",
                "Myanmar Kyat",
                "Namibian Dollar",
                "Australian Dollar",
                "Nepalese Rupee",
                "European Euro",
                "Cfp Franc",
                "New Zealand Dollar",
                "Nicaraguan Cordoba",
                "West African Cfa Franc",
                "Nigerian Naira",
                "New Zealand Dollar",
                "Australian Dollar",
                "United States Dollar",
                "North Korean Won",
                "Macedonian Denar",
                "Norwegian Krone",
                "Omani Rial",
                "Pakistani Rupee",
                "United States Dollar",
                "Israeli New Shekel",
                "United States Dollar",
                "Papua New Guinean Kina",
                "Paraguayan Guarani",
                "Peruvian Sol",
                "Philippine Peso",
                "New Zealand Dollar",
                "Polish Zloty",
                "European Euro",
                "United States Dollar",
                "Qatari Riyal",
                "European Euro",
                "Romanian Leu",
                "Russian Ruble",
                "Rwandan Franc",
                "United States Dollar",
                "European Euro",
                "Saint Helena Pound",
                "East Caribbean Dollar",
                "East Caribbean Dollar",
                "European Euro",
                "European Euro",
                "East Caribbean Dollar",
                "Samoan Tala",
                "European Euro",
                "Sao Tome And Principe Dobra",
                "Saudi Arabian Riyal",
                "Cfa Franc",
                "Serbian Dinar",
                "Seychellois Rupee",
                "Sierra Leonean Leone",
                "Singapore Dollar",
                "United States Dollar",
                "Netherlands Antillean Guilder",
                "European Euro",
                "European Euro",
                "Islands Dollar",
                "Somali Shilling",
                "South African Rand",
                "Pound Sterling",
                "South Korean Won",
                "South Sudanese Pound",
                "European Euro",
                "Sri Lankan Rupee",
                "Sudanese Pound",
                "Surinamese Dollar",
                "Norwegian Krone",
                "Swedish Krona",
                "Swiss Franc",
                "Syrian Pound",
                "New Taiwan Dollar",
                "Tajikistani Somoni",
                "Tanzanian Shilling",
                "Thai Baht",
                "United States Dollar",
                "West African Cfa Franc",
                "New Zealand Dollar",
                "Tongan Paanga",
                "Trinidad And Tobago Dollar",
                "Pound Sterling",
                "Tunisian Dinar",
                "Turkish Lira",
                "Turkmen Manat",
                "United States Dollar",
                "Australian Dollar",
                "Ugandan Shilling",
                "Ukrainian Hryvnia",
                "Uae Dirham",
                "Pound Sterling",
                "United States Dollar",
                "Uruguayan Peso",
                "United States Dollar",
                "Uzbekistani Som",
                "Vanuatu Vatu",
                "European Euro",
                "Venezuelan Bolivar",
                "Vietnamese Dong",
                "United States Dollar",
                "Cfp Franc",
                "Yemeni Rial",
                "Zambian Kwacha",
                "United States Dollar"]
    
    return currency